/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.mp.TSP.ui;

import java.awt.Color;
import java.awt.Graphics;
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import de.mp.TSP.domain.clustering.NeuronCluster;
import de.mp.TSP.domain.clustering.TownCluster;
import de.mp.TSP.domain.positions.Neuron;
import de.mp.TSP.domain.positions.Position;
import de.mp.TSP.domain.positions.Town;
import de.mp.TSP.logic.Computation;
import de.mp.TSP.util.Initializer;
import de.mp.TSP.util.XmlInputReader;

/**
 * 
 * @author mp
 */
public class TSP_GUI extends javax.swing.JFrame {

	private static final long serialVersionUID = 483428915115713205L;
	private boolean townsSet;

	/**
	 * Creates new form TSP_GUI
	 */
	public TSP_GUI() {

		initComponents();
		customInit();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jSlider1 = new javax.swing.JSlider();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jSlider2 = new javax.swing.JSlider();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jSlider3 = new javax.swing.JSlider();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jSlider4 = new javax.swing.JSlider();
		jLabel2 = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jPanel7 = new javax.swing.JPanel();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jLabel13 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel16 = new javax.swing.JLabel();
		jButton5 = new javax.swing.JButton();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		menuBar = new javax.swing.JMenuBar();
		editMenu = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		contentsMenuItem = new javax.swing.JMenuItem();
		aboutMenuItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(0, 102, 102));
		setLocationByPlatform(true);
		setResizable(false);

		jLayeredPane1.setBackground(new java.awt.Color(0, 255, 0));
		jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(
				new java.awt.Color(152, 164, 168), 3));

		jPanel1.setBackground(new java.awt.Color(0, 204, 153));
		jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jPanel1MouseReleased(evt);
			}
		});
		jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				jPanel1KeyReleased(evt);
			}
		});

		jPanel2.setBackground(new java.awt.Color(0, 51, 102));
		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 671,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 646,
				Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout
						.createSequentialGroup()
						.addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 5, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		jPanel1.setBounds(0, 0, 680, 650);
		jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jPanel3.setBackground(new java.awt.Color(200, 216, 221));
		jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(
				new java.awt.Color(176, 189, 193), 2));

		jSlider1.setBackground(new java.awt.Color(200, 216, 221));
		jSlider1.setMajorTickSpacing(1);
		jSlider1.setMaximum(200);
		jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jSlider1StateChanged(evt);
			}
		});

		jLabel1.setText("Neuronenanzahl");

		jLabel3.setForeground(new java.awt.Color(0, 153, 153));
		jLabel3.setText("jLabel3");

		jLabel4.setText("Lernrate");

		jSlider2.setBackground(new java.awt.Color(200, 216, 221));
		jSlider2.setForeground(new java.awt.Color(200, 216, 221));
		jSlider2.setMajorTickSpacing(1);
		jSlider2.setValue(90);
		jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jSlider2StateChanged(evt);
			}
		});

		jLabel5.setForeground(new java.awt.Color(51, 153, 0));
		jLabel5.setText("jLabel5");

		jLabel6.setText("Empirischer Faktor");

		jSlider3.setBackground(new java.awt.Color(200, 216, 221));
		jSlider3.setMajorTickSpacing(1);
		jSlider3.setSnapToTicks(true);
		jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jSlider3StateChanged(evt);
			}
		});

		jLabel7.setForeground(new java.awt.Color(51, 153, 0));
		jLabel7.setText("jLabel7");

		jLabel8.setText("Iterationen");

		jLabel9.setForeground(new java.awt.Color(51, 153, 0));
		jLabel9.setText("jLabel9");

		jSlider4.setBackground(new java.awt.Color(200, 216, 221));
		jSlider4.setForeground(new java.awt.Color(0, 204, 153));
		jSlider4.setMajorTickSpacing(1);
		jSlider4.setMaximum(5000);
		jSlider4.setValue(1000);
		jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jSlider4StateChanged(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel2.setText("Experimental-Panel");

		jPanel6.setBackground(new java.awt.Color(221, 239, 244));
		jPanel6.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

		jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		jButton2.setText("Karte bereinigen");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		jButton1.setText("Topologie setzen");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jButton2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jButton1)
										.addContainerGap()));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton2)
														.addComponent(jButton1))
										.addGap(24, 24, 24)));

		jPanel7.setBackground(new java.awt.Color(221, 239, 244));
		jPanel7.setBorder(javax.swing.BorderFactory
				.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

		jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		jButton3.setText("Approximieren");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		jButton4.setText("Konsolidieren");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout
				.setHorizontalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jButton4)
										.addContainerGap()));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton3)
														.addComponent(jButton4))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel6,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jSlider3,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jSlider2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jSlider1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel3))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel5))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel7))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel8)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel9))
														.addComponent(
																jSlider4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addComponent(
																jPanel7,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jPanel6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												48, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(jLabel3))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSlider1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(jLabel5))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSlider2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(jLabel7))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSlider3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(jLabel9))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSlider4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		jPanel5.setBackground(new java.awt.Color(200, 216, 221));
		jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(
				new java.awt.Color(152, 164, 168), 2));

		jLabel13.setForeground(new java.awt.Color(153, 153, 0));
		jLabel13.setText("jLabel13");

		jLabel12.setText("TSP-LE (Ringlänge)");

		jLabel11.setForeground(new java.awt.Color(0, 153, 153));
		jLabel11.setText("jLabel11");

		jLabel10.setText("Anzahl der Städte");

		jLabel15.setForeground(new java.awt.Color(0, 153, 153));
		jLabel15.setText("jLabel15");

		jLabel14.setText("Anzahl der konsolidierten Neuronen");

		jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel17.setText("Info-Panel");

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel5Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel13)
														.addComponent(jLabel11)
														.addComponent(jLabel10)
														.addComponent(
																jLabel12,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																184,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel14)
														.addComponent(jLabel15))
										.addContainerGap())
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel17)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel5Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel17)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel14)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel15)
										.addGap(21, 21, 21)
										.addComponent(jLabel10)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel11)
										.addGap(42, 42, 42)
										.addComponent(jLabel12)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel13)
										.addContainerGap()));

		jPanel4.setBackground(new java.awt.Color(200, 216, 221));
		jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(
				new java.awt.Color(152, 164, 168), 2));

		jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel16.setText("Test-Panel");

		jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		jButton5.setText("cities.xml laden und simulieren");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jLabel18.setText("Neuronenanzahl");

		jLabel19.setText("Lernrate");

		jLabel20.setText("Empirischer Faktor");

		jLabel21.setText("Iterationen");

		jTextField1.setBackground(new java.awt.Color(191, 225, 236));
		jTextField1.setForeground(new java.awt.Color(0, 0, 255));
		jTextField1.setText("jTextField1");

		jTextField2.setBackground(new java.awt.Color(191, 225, 236));
		jTextField2.setForeground(new java.awt.Color(0, 0, 255));
		jTextField2.setText("jTextField2");

		jTextField3.setBackground(new java.awt.Color(191, 225, 236));
		jTextField3.setForeground(new java.awt.Color(0, 0, 255));
		jTextField3.setText("jTextField3");

		jTextField4.setBackground(new java.awt.Color(191, 225, 236));
		jTextField4.setForeground(new java.awt.Color(0, 0, 255));
		jTextField4.setText("jTextField4");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jButton5,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel20)
																		.addComponent(
																				jTextField3))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel21)
																		.addComponent(
																				jTextField4))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel19)
																		.addComponent(
																				jTextField2))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel16)
																		.addGap(33,
																				33,
																				33))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel18)
																		.addComponent(
																				jTextField1)))
										.addContainerGap()));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel16)
										.addGap(51, 51, 51)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel18)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel19)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel20)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel21)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												104, Short.MAX_VALUE)
										.addComponent(jButton5)
										.addContainerGap()));

		editMenu.setMnemonic('e');
		editMenu.setText("Menü");

		jMenuItem1.setText("Lese XML");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		editMenu.add(jMenuItem1);

		contentsMenuItem.setMnemonic('c');
		contentsMenuItem.setText("Hilfe");
		contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				contentsMenuItemActionPerformed(evt);
			}
		});
		editMenu.add(contentsMenuItem);

		aboutMenuItem.setMnemonic('a');
		aboutMenuItem.setText("About");
		aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				aboutMenuItemActionPerformed(evt);
			}
		});
		editMenu.add(aboutMenuItem);

		menuBar.add(editMenu);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jPanel4,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jPanel5,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addGap(2, 2, 2)
								.addComponent(jLayeredPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										600,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(2, 2, 2)
								.addComponent(jPanel3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
																.addGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		layout.createSequentialGroup()
																				.addComponent(
																						jPanel4,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGap(2,
																						2,
																						2)
																				.addComponent(
																						jPanel5,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))
																.addComponent(
																		jLayeredPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		600,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(
														jPanel3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void contentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		Help h = new Help();
		h.setVisible(true);
	}

	private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		About a = new About();
		a.setVisible(true);
	}

	private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {
	}

	private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {
		if (!townsSet) {
			Graphics gra = jPanel1.getGraphics();
			gra.setColor(Color.darkGray);
			gra.drawRect(evt.getX() - 3, evt.getY() - 3, 7, 7);
			gra.setColor(Color.CYAN);
			gra.fillRect(evt.getX() - 2, evt.getY() - 2, 6, 6);
			TownCluster.getInstance().getCluster()
					.add(new Town(evt.getX(), evt.getY()));
			jLabel11.setText(String.valueOf(Integer.parseInt(jLabel11.getText()) + 1));
		}
	}

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser fc = new JFileChooser();
		fc.setCurrentDirectory(new File("./res"));
		int returnVal = fc.showOpenDialog(TSP_GUI.this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			XmlInputReader.getInstance().readXMLFile(fc.getSelectedFile());
			for (Position p : TownCluster.getInstance().getCluster()) {
				Graphics gra = jPanel1.getGraphics();
				gra.setColor(Color.darkGray);
				gra.drawRect(p.getPosition_x() - 3, p.getPosition_y() - 3, 7, 7);

				gra.setColor(Color.CYAN);
				gra.fillRect(p.getPosition_x() - 2, p.getPosition_y() - 2, 6, 6);

				jLabel11.setText(String.valueOf(TownCluster.getInstance()
						.getCluster().size()));
			}
		}

	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		Computation.getInstance().consolidate();
		jLabel13.setText(String.valueOf(Computation.getInstance()
				.getRoundtripLenght()) + " (konsolidiert)");
		jLabel15.setText(String.valueOf(NeuronCluster.getInstance()
				.getCluster().size()));
		jButton3.setEnabled(false);
		jButton4.setEnabled(false);
		updateLayer();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		Computation.getInstance().runApproximation(
				Double.parseDouble(jLabel5.getText()),
				Double.parseDouble(jLabel7.getText()),
				Integer.parseInt(jLabel9.getText()));
		jLabel13.setText(String.valueOf(Computation.getInstance()
				.getRoundtripLenght()));
		this.updateLayer();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		townsSet = true;
		jButton1.setEnabled(false);
		enableParameterBox();
		Initializer.getInstance().initializeNeuronCluster(
				Integer.parseInt(jLabel3.getText()), TownCluster.getInstance());

	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		jPanel1.repaint();
		jPanel2.repaint();
		jLabel11.setText("0");
		jLabel15.setText("0");
		jLabel13.setText("0");
		jButton1.setEnabled(true);
		townsSet = false;
		disableParameterBox();
		Initializer.getInstance().reset();
	}

	private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {
		jLabel9.setText(String.valueOf(jSlider4.getValue()));
	}

	private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {
		jLabel7.setText(String.valueOf((double) jSlider3.getValue() / 100));
	}

	private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {
		jLabel5.setText(String.valueOf((double) jSlider2.getValue() / 100));
	}

	private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {
		jLabel3.setText(String.valueOf(jSlider1.getValue()));
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		 Initializer.getInstance().reset();
		 XmlInputReader.getInstance().readXMLFile(new File("res/cities.xml"));
		 for (Position p : TownCluster.getInstance().getCluster())
		 {
			 Graphics gra = jPanel1.getGraphics();
			 gra.setColor(Color.darkGray);
			 gra.drawRect(p.getPosition_x()-3, p.getPosition_y()-3, 7, 7);
			 gra.setColor(Color.CYAN);
			 gra.fillRect(p.getPosition_x()-2, p.getPosition_y()-2, 6, 6);
			 jLabel11.setText(String.valueOf(TownCluster.getInstance().getCluster().size()));
		 }
		 Initializer.getInstance().initializeNeuronCluster(
				 Integer.valueOf(jTextField1.getText()), TownCluster.getInstance());
		 double runtime = Computation.getInstance().runApproximation(
				 Double.valueOf(jTextField2.getText()),
				 Double.valueOf(jTextField3.getText()), 
				 Integer.valueOf(jTextField4.getText()));
		 Computation.getInstance().consolidate();
		 jLabel13.setText(String.valueOf(Computation.getInstance().getRoundtripLenght())+" (konsolidiert)");
		 jLabel15.setText(String.valueOf(NeuronCluster.getInstance().getCluster().size()));
		 updateLayer(); 
		 JOptionPane.showMessageDialog(this, "Laufzeit "+runtime+ "ms");
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TSP_GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TSP_GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TSP_GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TSP_GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TSP_GUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JMenuItem contentsMenuItem;
	private javax.swing.JMenu editMenu;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JSlider jSlider1;
	private javax.swing.JSlider jSlider2;
	private javax.swing.JSlider jSlider3;
	private javax.swing.JSlider jSlider4;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JMenuBar menuBar;

	// End of variables declaration

	private void customInit() {
		townsSet = false;
		jLabel11.setText("0");
		jLabel13.setText("0");
		jLabel3.setText(String.valueOf(jSlider1.getValue()));
		jLabel5.setText(String.valueOf((double) jSlider2.getValue() / 100));
		jLabel7.setText(String.valueOf((double) jSlider3.getValue() / 100));
		jLabel9.setText(String.valueOf(jSlider4.getValue()));
		jLabel15.setText("0");
		jTextField1.setText("200");
		jTextField2.setText("0.9");
		jTextField3.setText("0.5");
		jTextField4.setText("1000");
		disableParameterBox();
	}

	private void disableParameterBox() {
		jSlider1.setEnabled(true);
		jSlider2.setEnabled(false);
		jSlider3.setEnabled(false);
		jSlider4.setEnabled(false);
		jButton3.setEnabled(false);
		jButton4.setEnabled(false);
	}

	private void enableParameterBox() {
		jSlider1.setEnabled(false);
		jSlider2.setEnabled(true);
		jSlider3.setEnabled(true);
		jSlider4.setEnabled(true);
		jButton3.setEnabled(true);
		jButton4.setEnabled(true);
	}

	private void updateLayer() {
		Graphics gra = jPanel2.getGraphics();
		jPanel2.update(gra);
		for (Position p : TownCluster.getInstance().getCluster()) {
			gra.setColor(Color.ORANGE);
			gra.drawRect(p.getPosition_x() - 5, p.getPosition_y() - 5, 11, 11);
			gra.setColor(Color.MAGENTA);
			gra.fillRect(p.getPosition_x() - 2, p.getPosition_y() - 2, 6, 6);
			gra.setColor(Color.ORANGE);
			gra.fillRect(p.getPosition_x() - 1, p.getPosition_y() - 1, 4, 4);
		}
		for (Position p : NeuronCluster.getInstance().getCluster()) {
			Neuron n = (Neuron) p;
			gra.setColor(Color.GREEN);
			gra.drawRect(p.getPosition_x() - 2, p.getPosition_y() - 2, 4, 4);
			gra.setColor(Color.CYAN);
			gra.drawLine(n.getPosition_x(), n.getPosition_y(), n
					.getNeighbour_prev().getPosition_x(), n.getNeighbour_prev()
					.getPosition_y());
		}
	}

}
